<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="15" passed="12">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="215197" started-at="2019-12-14T22:36:13 CET" finished-at="2019-12-14T22:39:48 CET">
    <groups>
    </groups>
    <test name="Default test" duration-ms="215197" started-at="2019-12-14T22:36:13 CET" finished-at="2019-12-14T22:39:48 CET">
      <class name="tests.PHPTravelsTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:tests.PHPTravelsTest@627551fb]" name="setup" is-config="true" duration-ms="10546" started-at="2019-12-14T22:36:13 CET" finished-at="2019-12-14T22:36:24 CET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="login()[pri:0, instance:tests.PHPTravelsTest@627551fb]" name="login" duration-ms="20654" started-at="2019-12-14T22:36:24 CET" finished-at="2019-12-14T22:36:44 CET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="menuUpdates()[pri:1, instance:tests.PHPTravelsTest@627551fb]" name="menuUpdates" duration-ms="10106" started-at="2019-12-14T22:36:44 CET" finished-at="2019-12-14T22:36:55 CET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- menuUpdates -->
        <test-method status="PASS" signature="menuDashboard()[pri:2, instance:tests.PHPTravelsTest@627551fb]" name="menuDashboard" duration-ms="8011" started-at="2019-12-14T22:36:55 CET" finished-at="2019-12-14T22:37:03 CET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- menuDashboard -->
        <test-method status="PASS" signature="menuModules()[pri:3, instance:tests.PHPTravelsTest@627551fb]" name="menuModules" duration-ms="6500" started-at="2019-12-14T22:37:03 CET" finished-at="2019-12-14T22:37:09 CET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- menuModules -->
        <test-method status="PASS" signature="menuNewTours()[pri:4, instance:tests.PHPTravelsTest@627551fb]" name="menuNewTours" duration-ms="9378" started-at="2019-12-14T22:37:09 CET" finished-at="2019-12-14T22:37:18 CET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- menuNewTours -->
        <test-method status="PASS" signature="menuCars()[pri:5, instance:tests.PHPTravelsTest@627551fb]" name="menuCars" duration-ms="11375" started-at="2019-12-14T22:37:18 CET" finished-at="2019-12-14T22:37:30 CET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- menuCars -->
        <test-method status="PASS" signature="menuCoupons()[pri:6, instance:tests.PHPTravelsTest@627551fb]" name="menuCoupons" duration-ms="7082" started-at="2019-12-14T22:37:30 CET" finished-at="2019-12-14T22:37:37 CET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- menuCoupons -->
        <test-method status="PASS" signature="menuNewsletter()[pri:7, instance:tests.PHPTravelsTest@627551fb]" name="menuNewsletter" duration-ms="6337" started-at="2019-12-14T22:37:37 CET" finished-at="2019-12-14T22:37:43 CET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- menuNewsletter -->
        <test-method status="PASS" signature="menuBookings()[pri:8, instance:tests.PHPTravelsTest@627551fb]" name="menuBookings" duration-ms="6473" started-at="2019-12-14T22:37:43 CET" finished-at="2019-12-14T22:37:50 CET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- menuBookings -->
        <test-method status="FAIL" signature="cars()[pri:9, instance:tests.PHPTravelsTest@627551fb]" name="cars" duration-ms="14432" started-at="2019-12-14T22:37:50 CET" finished-at="2019-12-14T22:38:04 CET">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [10] but found [40]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [10] but found [40]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at tests.PHPTravelsTest.cars(PHPTravelsTest.java:132)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cars -->
        <test-method status="PASS" signature="ordersCount()[pri:10, instance:tests.PHPTravelsTest@627551fb]" name="ordersCount" duration-ms="17532" started-at="2019-12-14T22:38:04 CET" finished-at="2019-12-14T22:38:22 CET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ordersCount -->
        <test-method status="PASS" signature="carsExtras()[pri:11, instance:tests.PHPTravelsTest@627551fb]" name="carsExtras" duration-ms="33945" started-at="2019-12-14T22:38:22 CET" finished-at="2019-12-14T22:38:56 CET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- carsExtras -->
        <test-method status="PASS" signature="carsExtrasImage()[pri:12, instance:tests.PHPTravelsTest@627551fb]" name="carsExtrasImage" duration-ms="2133" started-at="2019-12-14T22:38:56 CET" finished-at="2019-12-14T22:38:58 CET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- carsExtrasImage -->
        <test-method status="FAIL" signature="carsExtrasPrice()[pri:13, instance:tests.PHPTravelsTest@627551fb]" name="carsExtrasPrice" duration-ms="16352" started-at="2019-12-14T22:38:58 CET" finished-at="2019-12-14T22:39:14 CET">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [35s00] but found [3500]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [35s00] but found [3500]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at tests.PHPTravelsTest.carsExtrasPrice(PHPTravelsTest.java:193)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- carsExtrasPrice -->
        <test-method status="FAIL" signature="changeCustomers()[pri:15, instance:tests.PHPTravelsTest@627551fb]" name="changeCustomers" duration-ms="34251" started-at="2019-12-14T22:39:14 CET" finished-at="2019-12-14T22:39:48 CET">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [mikamikic@gmail.com] but found [Entries not found.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [mikamikic@gmail.com] but found [Entries not found.]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at tests.PHPTravelsTest.changeCustomers(PHPTravelsTest.java:203)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- changeCustomers -->
        <test-method status="PASS" signature="quit()[pri:0, instance:tests.PHPTravelsTest@627551fb]" name="quit" is-config="true" duration-ms="0" started-at="2019-12-14T22:39:48 CET" finished-at="2019-12-14T22:39:48 CET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- tests.PHPTravelsTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
